### ISSUE TITLE
The pictures can't be displayed in email

### ISSUE THREAD

**Issue by heaseny** [vladwa/robot-email-template#5]
The pictures can't be displayed in email, how can I make it can be displayed?

![image](https://user-images.githubusercontent.com/35910818/115979370-2ea40a00-a5b8-11eb-9087-29e10ab49089.png)

**Comment by Lucifar2** [comment]
Same issue for me. Were you able to fix it @heaseny ? @vladwa can you help us here please

**Comment by heaseny** [comment]
My situation is the picture s can be displayed in Jenkins email testing, but not in email. That's because the URL in 'img'  is changed silently by the proxy server.   I changed the image URL to base64 data, It didn't display the images in email, but can display in email test. -----------------------------ThanksXuecun-------- 原始邮件 --------发件人： Saad Baig ***@***.***>日期： 2021年5月20日周四 凌晨2:36收件人： vladwa/robot-email-template ***@***.***>抄送： heaseny ***@***.***>, Mention ***@***.***>主    题： Re: [vladwa/robot-email-template] The pictures can't be displayed in email (#5)
Same issue for me. Were you able to fix it @heaseny ? @vladwa can you help us here please

**Comment by Lucifar2** [comment]
@heaseny Thanks for the reply. So you mean the images can be displayed in the email test on Jenkins and not in the real email we receive from Jenkins ? 
Yes, I also read about converting the image to base 64. Can you share me an example or may be you can share the .groovy file in which you made changes with base 64. 
So there is no way for us to see the image in the real email ?
Thank you :)

**Comment by Lucifar2** [comment]
@heaseny I just tested the same file with email template testing and I can see all the images correctly there.

**Comment by heaseny** [comment]
<img src=“data:image/jpg;base64, ${gif}"/>${gif} is the data of base64In this way the image can only be displayed in email test. I think the proxy server need to be reconfigured to support displaying the image. -----------------------------ThanksXuecun-------- 原始邮件 --------发件人： Saad Baig ***@***.***>日期： 2021年5月20日周四 傍晚6:24收件人： vladwa/robot-email-template ***@***.***>抄送： heaseny ***@***.***>, Mention ***@***.***>主    题： Re: [vladwa/robot-email-template] The pictures can't be displayed in email (#5)
@heaseny Thanks for the reply. So you mean the images can be displayed in the email test on Jenkins and not in the real email we receive from Jenkins ?
Yes, I also read about converting the image to base 64. Can you share me an example or may be you can share the .groovy file in which you made changes with base 64.
So there is no way for us to see the image in the real email ?
Thank you :)
